import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const src = process.argv[2] || '/tmp/kata-dasar.txt';
const raw = fs.readFileSync(src, 'utf8');
const words = raw.split('\n')
  .map(w => w.trim().toLowerCase())
  .filter(w => w.length > 0 && /^[a-z]/.test(w));

const additional = [
  // === IT & COMPUTER SCIENCE ===
  'kardinalitas','algoritma','algoritme','aplikasi','komputer','internet','software','hardware',
  'database','jaringan','sistem','digital','elektronik','teknologi',
  'informasi','komunikasi','program','developer','domain',
  'server','client','browser','platform',
  'akun','password','username','login','logout','register',
  'download','upload','update','delete','insert','convert',
  'format','config','setting','admin','panel','dashboard',
  'kecerdasan','buatan','pembelajaran','mesin','komputasi','awan',
  'blockchain','siber','keamanan','data','bigdata',
  'antarmuka','pengguna','enkripsi','dekripsi','sertifikat',
  'repo','repository','commit','branch','fork','clone','push','pull',
  'debug','deploy','hosting','cloud','cache','cookie','session',
  'token','api','endpoint','middleware','framework','library',
  'frontend','backend','fullstack','stack','database','query',
  'machinelearning','deeplearning','neuralnetwork','artificialintelligence',
  'responsive','scalable','optimasi','refaktor','refactoring',

  // === LINGUISTICS & LANGUAGE ===
  'persamaan','sinonim','antonim','definisi','istilah','kamus',
  'translate','terjemahan','bahasa','indonesia','inggris','global',
  'leksikal','makna','morfologi','fonetik',
  'fonem','afiks','prefiks','sufiks','infiks',
  'konfiks','reduplikasi','frase','klausa',
  'kalimat','paragraf','wacana','semantik',
  'pragmatik','sintaksis','etimologi',
  'leksikografi','leksikologi','terminologi',
  'tesaurus','glosarium','indeks',
  'sinonimitas','polisemi','homonim','hiponim',
  'hipernim','meronim','antonimi',
  'kolokasi','idiom','metafora',
  'konotasi','denotasi','referensi','relasi',
  'gramatikal','leksem','morfem','fonologi','fonetik',
  'morfosintaksis','ortografi','dialek','idiolek','sosiolek',
  'register','ragam','laras','wacana','pragmatik',
  'toponimi','antroponimi','onim','etnis',
  'diglosia','bilingual','monolingual','multilingual',
  'alihkode','campurkode','interferensi','integrasi',
  'akuisisi','pemerolehan','pembelajaran','pengajaran',
  'resepsi','produksi','kompetensi','performansi',

  // === ACADEMIC & GENERAL ===
  'analisis','statistik','grafik','tabel','laporan','dokumen',
  'abstraksi','kontemplasi','akumulasi','determinasi',
  'eksplanasi','interpretasi','klarifikasi','prediksi',
  'preskripsi','proyeksi','deduksi','induksi',
  'generalisasi','spesifikasi','diferensiasi',
  'artikulasi','formulasi','kalkulasi','kombinasi',
  'komparasi','kompilasi','komputasi','konsolidasi',
  'konvergensi','divergensi','koordinasi','koroborasi',
  'korelasi','korespondensi','kulminasi','kuantifikasi',
  'moderasi','multiplikasi','navigasi','negasi',
  'notasi','numerasi','operasionalisasi','optimum',
  'akademisi','aparat','kapabilitas',
  'multidisiplin','multilateral','multinasional',
  'pluralitas','pluralisme','sekularisme',
  'birokrat','karakter','komoditi','konsolidasi',
  'paradigma','parameter','regenerasi',
  'sinkronisasi','spesialisasi',
  'spiritualitas','subkontraktor',
  'supremasi','tanggungjawab',
  'transaksi','varian','veteran',
  'yurisdiksi','yurisprudensi',
  'administrasi','kapital','konfirmasi','eksploitasi',
  'eksplorasi','profesionalisme',
  'hakikat','implementatif','karakterisasi',
  'sosiologi','antropologi','ideologis',
  'interdisipliner','transdisipliner',
  'epistemologi','aksiologis','teleologis',
  'otentisitas','justifikasi','sistemik',
  'sistematis','sintesis','analitis',
  'metodologis','metodis',
  'empiris','teoretis','praktis',
  'mendasar','terpadu','menyeluruh',
  'berkesinambungan','berkelanjutan',
  'terintegrasi','terstandarisasi','terstruktur',
  'bersinergi','berkolaborasi','berpartisipasi',
  'berkontribusi','beradaptasi','berevolusi',
  'bertransformasi','berinovasi','berkreasi',
  'mengeksplorasi','mengidentifikasi',
  'mengklasifikasikan','mengimplementasikan',
  'memvalidasi','memverifikasi','mengonfirmasi',
  'berkoordinasi','berkonsultasi','bernegosiasi',
  'mengapresiasi','mengartikulasikan',
  'pengembangan','peningkatan','pengelolaan',
  'penyediaan','pemanfaatan','pemberdayaan',
  'pelaksanaan','penyelenggaraan','pengaturan',
  'pembinaan','pembentukan','penciptaan',
  'pengawasan','pengendalian','penilaian',
  'pemantauan','evaluasi','akreditasi',
  'fundamental','holistik','integral','filosofis',
  'teologis','sosiologis','antropologis',
  'metafisika','ontologi','epistemik',
  'heuristik','hermeneutika','fenomenologi',
  'dialektika','retorika','argumentasi',
  'postulat','premis','silogisme','proposisi',
  'kontradiksi','redundansi','superlasi',
  'kategoris','komparatif','superlatif',
  'preseden','prekursor','pelopor','perintis',

  // === SCIENCE (FISIKA, KIMIA, BIOLOGI) ===
  'spektroskopi','spektrometer','spektrum',
  'termodinamika','elektromagnetik','elektromagnetisme',
  'fisika','kimia','biologi','astronomi',
  'biokimia','biofisika','bioinformatika',
  'bioteknologi','nanoteknologi','mikrobiologi',
  'seluler','molekuler','atomik','nuklir',
  'reaksi','reaktan','produk','katalis','katalisator',
  'enzim','substrat','inhibitor','aktivator',
  'fotosintesis','respirasi','fermentasi',
  'oksidasi','reduksi','hidrolisis','sintesis',
  'polimer','monomer','karbohidrat','protein','lipid',
  'asamnukleat','dna','rna','nukleotida',
  'genom','genetika','kromosom','alel',
  'fenotipe','genotipe','mutasi','evolusi',
  'ekologi','habitat','biodiversitas','keanekaragaman',
  'biosfer','litosfer','hidrosfer','atmosfer',
  'ekosistem','populasi','komunitas','niche',
  'adaptasi','seleksi','alamiah','survival',
  'organisme','metabolisme','anabolisme','katabolisme',
  'homeostasis','endokrin','imunitas','imunologi',
  'mekanisme','fisiologi','histologi','sitologi',
  'entomologi','ornitologi','herpetologi','mamologi',
  'botani','zoologi','mikologi','bakteriologi',
  'virologi','parasitologi','patologi','epidemiologi',
  'farmakologi','toksikologi','teratologi',
  'limnologi','oseanografi','klimatologi','meteorologi',
  'geologi','mineralogi','petrologi','paleontologi',
  'seismologi','vulkanologi','geomorfologi',
  'astronomi','astrofisika','kosmologi','planetologi',
  'spektroskopi','kromatografi','elektroforesis',
  'sentrifugasi','mikroskopi','turbidimetri',
  'kalorimetri','konduktivitas','viskositas',
  'densitas','porositas','permeabilitas',
  'elastisitas','plastisitas','duktilitas',
  'kristalografi','kristalisasi','polimorfisme',
  'isotop','isobar','isoton','isomer',
  'konfigurasi','konformasi','isomerisasi',

  // === MEDICAL & HEALTH ===
  'diagnosis','diagnostik','prognosis','terapi','terapeutik',
  'preventif','kuratif','paliatif','rehabilitatif',
  'imunisasi','vaksinasi','vaksin','antibodi','antigen',
  'epidemi','pandemi','endemi','wabah','infeksi',
  'kardiologi','neurologi','onkologi','pediatri',
  'geriatri','obstetri','ginekologi','urologi',
  'nefrologi','pulmonologi','hepatologi','gastroenterologi',
  'dermatologi','oftalmologi','otorinolaringologi',
  'psikiatri','radiologi','patologi','anestesi',
  'bedah','internis','pediatri','neonatologi',
  'kardiovaskular','sirkulasi','respirasi','digesti',
  'hemoglobin','leukosit','trombosit','plasma',
  'arteri','vena','kapiler','aorta',
  'simptom','gejala','sindrom','patogenesis',
  'etiologi','komorbiditas','mortalitas','morbiditas',
  'insidensi','prevalensi','survival','remisi',
  'klinis','laboratoris','farmasi','medikasi',
  'antibiotik','analgesik','antipiretik','antiinflamasi',
  'antivirus','antifungi','antibakteri','antiseptik',
  'kemoterapi','radioterapi','imunoterapi','bedah',
  'skrining','diagnosis','dini','stadium','klasifikasi',
  'rehabilitasi','fisioterapi','okupasi','terapi',
  'nutrisi','gizi','dietetik','metabolik',
  'homeopati','akupunktur','kiropraktik','naturopati',
  'epidemiologi','biostatistik','kesehatan','masyarakat',
  'sanitasi','higiene','sterilisasi','desinfeksi',

  // === LAW ===
  'hukum','pidana','perdata','tata','negara',
  'konstitusi','undangundang','peraturan','yurisprudensi',
  'yurisdiksi','litigasi','arbitrase','mediasi',
  'ajudikasi','banding','kasasi','gugatan',
  'delik','pidana','perdata','putusan','vonis',
  'eksekusi','sita','sitaan','lelang','fidusia',
  'notaris','ppat','advokat','pengacara','jaksa',
  'hakim','panitera','jurusita','polisi',
  'kuhp','kuhperdata','kuhdagang','kuhap',
  'korporasi','kolusi','nepotisme','gratifikasi',
  'tipikor','korupsi','suap','pencucian','uang',
  'delik','aduan','biasa','pelanggaran','kejahatan',
  'percobaan','permufakatan','pembantuan','penyertaan',
  'pidana','bersyarat','denda','kurungan','penjara',
  'seumur','hidup','mati','tambahan',
  'restitusi','kompensasi','ganti','rugi',
  'perjanjian','kontrak','akta','pernyataan',
  'waris','wasiat','hibah','saham','obligasi',
  'paten','hakcipta','merek','indikasi','geografis',
  'desain','industri','rahasia','dagang',
  'inkrah','tetap','kekuatan','hukum',
  'somasi','teguran','peringatan','sekaligus',

  // === ECONOMICS & BUSINESS ===
  'ekonomi','mikroekonomi','makroekonomi','moneter','fiskal',
  'inflasi','deflasi','resesi','depresi','ekspansi',
  'resiliensi','recovery','boom','bubble','crash',
  'neraca','laporan','arus','kas','akuntansi',
  'pajak','retribusi','bea','cukai','tarif',
  'dividen','profit','laba','rugi','margin',
  'likuiditas','solvabilitas','rentabilitas','profitabilitas',
  'efisiensi','efektivitas','produktivitas',
  'aset','liabilitas','ekuitas','modal','saham',
  'obligasi','reksadana','deposito','giro','tabungan',
  'kredit','debit','pinjaman','pembiayaan','anuitas',
  'investasi','spekulasi','hedging','diversifikasi',
  'pasar','modal','bursa','efek','sekuritas',
  'bank','sentral','komersial','syariah','digital',
  'fintech','peer-to-peer','crowdfunding','mobilebanking',
  'polis','asuransi','premi','klaim','underwriting',
  'reasuransi','koasuransi','deductible',
  'koperasi','umkm','persero','pt','cv','firma',
  'manajemen','strategi','operasional','pemasaran',
  'branding','segmentasi','targeting','positioning',
  'anggaran','forecasting','budgeting','audit',
  'akuntansi','keuangan','perbankan','pasar', 'modal',
  'obligor','kreditur','debitor','ekuitas',
  'sukuk','wakat','zakat','infaq','sedekah',

  // === PSYCHOLOGY ===
  'kognitif','afektif','psikomotor','behavioral',
  'psikologi','klinis','perkembangan','pendidikan',
  'industri','organisasi','sosial','kepribadian',
  'kognisi','persepsi','atensi','memori',
  'belajar','thinking','problem','solving',
  'emosi','motivasi','inteligensi','kreativitas',
  'psikometri','tes','ukur','skala','inventori',
  'psikopatologi','skizofrenia','depresi','anxiety',
  'bipolar','ocd','ptsd','adhd','autisme',
  'konseling','psikoterapi','terapi','perilaku',
  'kognitif','humanistik','psikoanalisis','transpersonal',
  'psikodinamika','eksistensial','gestalt',
  'konseling','bimbingan','arahan','karier',
  'psikotest','minat','bakat','kepribadian',
  'observasi','wawancara','kuesioner','angket',
  'statistik','parametrik','nonparametrik','korelasi',
  'regresi','anova','faktor','analisis',
  'validitas','reliabilitas','standarisasi','norma',
  'mental','sehat','gangguan','jiwa','psikososial',
  'resiliensi','adaptasi','koping','stres',
  'burnout','wellbeing','kesejahteraan','subyektif',
  'mindfulness','meditasi','relaksasi','hipnoterapi',
  'neuropsikologi','psikofarmakologi','psikoneuroimunologi',
  'psikosomatis','konversi','somatisasi',

  // === EDUCATION ===
  'pedagogi','andragogi','heutagogi','didaktik',
  'kurikulum','silabus','rpp','tujuan','pembelajaran',
  'indikator','kompetensi','dasar',
  'evaluasi','asesmen','formatif','sumatif',
  'portofolio','proyek','presentasi','tes',
  'kognitif','afektif','psikomotorik','dimensi',
  'pengetahuan','pemahaman','aplikasi','sintesis',
  'pembelajaran','aktif','kooperatif','kolaboratif',
  'kontekstual','berbasis','masalah','proyek',
  'inkuiri','penemuan','ekspositori','ceramah',
  'tutorial','seminar','workshop','simposium',
  'konferensi','lokakarya','sarasehan','diskusi',
  'kuliah','praktikum','responsi','bimbingan',
  'skripsi','tesis','disertasi','penelitian',
  'kualitatif','kuantitatif','mixed','method',
  'survei','studi','kasus','eksperimen','tindakan',
  'library','research','studi','pustaka','dokumentasi',
  'akreditasi','sertifikasi','standarisasi','mutu',
  'ijazah','transkrip','sks','ipk','cumlaude',
  'beasiswa','bidikmisi','lpdp','swadaya',
  'fakultas','jurusan','prodi','departemen',
  'rektor','dekan','kaprodi','dosen','pengajar',
  'guru','siswa','mahasiswa','peserta','didik',
  'pintar','cerdas','berbakat','istimewa',
  'luarbiasa','inklusi','difabel','bakat',

  // === ENVIRONMENT ===
  'lingkungan','hidup','ekologi','biodiversitas',
  'keanekaragaman','hayati','sumberdaya','alam',
  'konservasi','preservasi','restorasi','reklamasi',
  'emisi','gas','rumahkaca','karbon','jejak',
  'polusi','pencemaran','limbah','sampah',
  'plastik','mikroplastik','organik','anorganik',
  'daurulang','reuse','reduce','recycle',
  'energi','terbarukan','surya','angin','air',
  'panasbumi','biomassa','nuklir','hidro',
  'degradasi','desertifikasi','deforestasi',
  'reboisasi','penghijauan','penanaman','kembali',
  'bencana','alam','gempa','tsunami','banjir',
  'longsor','erupsi','angin','puting','beliung',
  'iklim','cuaca','pemanasan','global','perubahan',
  'adaptasi','mitigasi','resiliensi','kerentanan',
  'keberlanjutan','berkelanjutan','lestari','hijau',
  'ekoefisiensi','ekologi','industri',
  'keadilan','lingkungan','ekosentris','biosentris',
  'rewilding','karbon','netral','netzero',
  'solarpanel','turbin','angin','pembangkitlistrik',

  // === STATISTICS & RESEARCH ===
  'analisis','data','statistik','parametrik','nonparametrik',
  'deskriptif','inferensial','multivariat','bivariat',
  'univariat','univariat','bivariat','multivariat',
  'regresi','linier','logistik','multiple',
  'korelasi','pearson','spearman','khi','kuadrat',
  'uji','validitas','reliabilitas','normalitas',
  'homogenitas','linieritas','signifikansi',
  'hipotesis','nol','alternatif','arah',
  'satu','dua','sisi','pvalue','alpha',
  'populasi','sampel','random','purposive',
  'stratified','cluster','accidental','snowball',
  'variabel','independen','dependen','kontinu',
  'diskrit','nominal','ordinal','interval',
  'instrumen','kuesioner','skala','likert',
  'wawancara','observasi','dokumentasi','triangulasi',
  'mean','median','modus','standar','deviasi',
  'varians','range','minimal','maksimal',
  'frekuensi','persentase','proporsi','rasio',
  'validasi','reliabilitasi','normalitas','homogenitas',
  'eksperimen','kontrol','treatment','randomisasi',
  'longitudinal','crosssectional','retrospektif',
  'prospektif','kohort','kasus','kontrol',
  'etnografi','fenomenologi','grounded','teori',
  'studikasus','narrative','analisis','konten',

  // === MATHEMATICS ===
  'aljabar','kalkulus','geometri','trigonometri',
  'statistika','probabilitas','optimasi','kalkulasi',
  'diferensial','integral','limit','turunan',
  'matriks','determinan','vektor','skalar',
  'fungsi','persamaan','pertidaksamaan','logaritma',
  'eksponen','rasional','irasional','bilangan',
  'prima','komposit','faktor','kelipatan',
  'himpunan','relasi','logika','matematika',
  'deret','barisan','konvergen','divergen',
  'dimensi','ruang','bidang','titik','garis',
  'sudut','segitiga','segiempat','lingkaran',
  'teorema','lemma','corollary','aksioma',
  'postulat','definisi','konjektur','pembuktian',

  // === OTHER COMMON ===
  'absurd','akses','aktivitas','aktual','alternatif','antisipasi',
  'apresiasi','artikel','asosiasi','atraksi','autentik',
  'baterai','birokrasi','brilian',
  'dampak','dedikasi','defisit','dekorasi','delusi','demokrasi',
  'departemen','depresi','deteksi','dialog','diplomasi',
  'disiplin','diskriminasi','distribusi','doktrin','dominasi',
  'edukasi','efektif','efisien','eksis','eksklusif','ekspansi',
  'favorit','fenomena','figur','final','fleksibel',
  'fokus','formulir','frekuensi','fungsi',
  'generasi','genius','genre',
  'harmonis','heroik','hierarki','homogen',
  'ideologi','ilustrasi','imajinasi','indikasi','industri',
  'inisiatif','inovasi','inspirasi','insting','integritas',
  'intelektual','intensif','interaksi','interpretasi','intuisi',
  'investigasi','ironi','isolasi',
  'kapasitas','kapitalis','karakteristik','kategori','koleksi',
  'kombinasi','kompetisi','kompleks','komponen','konsekuensi',
  'konsisten','konstruksi','kontaminasi','kontribusi',
  'korporasi','kreativitas','kredibilitas','krisis','kriteria',
  'kronologi','kualitas','kuantitas',
  'legalitas','legenda','legitimasi','liberal','likuidasi',
  'literatur','logika','loyalitas',
  'mayoritas','mekanisme','mentalitas','minoritas','misteri',
  'mobilitas','modern','monopoli','moralitas','motivasi',
  'narasi','nasional','natural','negosiasi','netral','norma',
  'objektif','obsesi','oksigen','opini','optimis',
  'orasi','orientasi','orisinal','otonomi',
  'paradoks','paralel',
  'penetrasi','persepsi','perspektif','pesimis',
  'populer','poros','posisi','potensi',
  'prediksi','preferensi','prestasi','prioritas',
  'profesional','progresif','proklamasi','proporsional','proteksi',
  'protokol','provokasi','psikologi','publikasi',
  'rasional','realitas','reformasi','regulasi',
  'relevan','religius','replikasi','representasi','reputasi',
  'respons','restorasi','revolusi','risiko','ritme','robotik',
  'sanksi','sastra','seleksi','sensasi','sensitif','sentral',
  'signifikan','simbolis','simpati','sinkron','situasi',
  'sosialisasi','spesialis','spesifik','spiritual','stabil',
  'standarisasi','stimulasi','strategi','struktur',
  'subjektif','substansi','sukses','superior','survei','simbol',
  'tabulasi','taktik','target','teknis','teknisi','toleransi',
  'tradisi','transformasi','transisi','transparan',
  'tren','turisme','universal','urban','utilitas',
  'validitas','variabel','variasi','versi','vibrasi','virtual',
  'virus','visi','visual','vital','volume','vulkanik',
  'kafe','restoran','supermarket',
  'freelance','komunitas','afiliasi',
  'arsitektur','rekomendasi',
  'federasi','fragmentasi','globalisasi',
  'harmoni','identitas','imigrasi',
  'institusi','integrasi','internasional','kabinet',
  'kapitalisme','koalisi','kolektivitas','komersial',
  'komite','kompensasi',
  'koneksi','konflik','kongres',
  'konteks','kontroversi','konvensi',
  'koordinat','korporat','kriminal','kristal',
  'kapital','korporasi','kolusi','nepotisme',
  'transparansi','akuntabilitas',
  'solvabilitas','likuiditas','rentabilitas'
];

const allWords = [...new Set([...words, ...additional])]
  .filter(w => /^[a-z]/.test(w) && w.length > 1)
  .sort();

// Write TypeScript source (for type safety)
const tsPath = path.join(__dirname, '..', 'src', 'data', 'id-words.ts');
const json = JSON.stringify(allWords);
const comment = '// Auto-generated from Sastrawi kata-dasar + additional words\n// Total: ' + allWords.length + ' words\n// biome-ignore format: autogenerated\n';
const js = comment + 'export const idWords: string[] = ' + JSON.stringify(allWords, null, 1) + ';\n';
fs.writeFileSync(tsPath, js);
console.log('Written', allWords.length, 'words to', tsPath);

// Write public JSON file (for dynamic client-side fetch)
const publicPath = path.join(__dirname, '..', 'public', 'id-words.json');
fs.writeFileSync(publicPath, json, 'utf8');
console.log('Written', allWords.length, 'words to', publicPath);
